[project]
name = "sweetshop"
version = "0.1.0"
description = "..."
readme = "README.md"
requires-python = ">=3.12"

[dependency-groups]
dev = ["ruff", "ty"]

[tool.ruff.lint]
extend-select = [
    "I", # isort
]
